# Fidelis Yoga Pradipta
# 2702296224
# UAS MODEL DEPLOYMENT
# GENAP = DATASET B (DATASET 2)

In [142]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [143]:
df = pd.read_csv('ObesityDataSet2.csv')
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,24,1.58,65.29,yes,no,2.03,2.74,Sometimes,no,2.00,no,1.28,1.019,no,Public_Transportation,Overweight_Level_II
1,Male,23,1.65,66.00,no,no,3.00,3.00,Sometimes,no,2.00,no,3.00,0.000,no,Public_Transportation,Normal_Weight
2,Female,21,1.69,51.26,yes,yes,3.00,3.18,Frequently,no,1.91,no,0.48,0.625,no,Public_Transportation,Insufficient_Weight
3,Female,22,1.69,65.00,yes,yes,2.00,3.00,Sometimes,no,2.00,no,1.00,1.000,Sometimes,Public_Transportation,Normal_Weight
4,Female,23,1.61,82.64,yes,yes,2.96,1.00,Sometimes,no,2.98,no,0.74,2.000,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,Female,21,1.74,130.93,yes,yes,3.00,3.00,Sometimes,no,1.85,no,1.46,0.962,Sometimes,Public_Transportation,Obesity_Type_III
1052,Female,17,1.54,57.26,no,yes,1.97,2.34,Sometimes,no,1.71,yes,0.10,1.191,Sometimes,Public_Transportation,Overweight_Level_I
1053,Female,19,1.60,45.00,no,no,3.00,3.00,no,no,3.00,yes,2.00,0.000,no,Walking,Insufficient_Weight
1054,Female,25,1.69,113.45,yes,yes,3.00,3.00,Sometimes,no,2.99,no,0.39,0.284,Sometimes,Public_Transportation,Obesity_Type_III
1055,Male,27,1.81,118.28,yes,yes,2.24,3.00,Sometimes,no,2.68,no,0.98,0.000,Sometimes,Public_Transportation,Obesity_Type_II

In [144]:
df.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,24,1.58,65.29,yes,no,2.03,2.74,Sometimes,no,2.00,no,1.28,1.019,no,Public_Transportation,Overweight_Level_II
1,Male,23,1.65,66.00,no,no,3.00,3.00,Sometimes,no,2.00,no,3.00,0.000,no,Public_Transportation,Normal_Weight
2,Female,21,1.69,51.26,yes,yes,3.00,3.18,Frequently,no,1.91,no,0.48,0.625,no,Public_Transportation,Insufficient_Weight
3,Female,22,1.69,65.00,yes,yes,2.00,3.00,Sometimes,no,2.00,no,1.00,1.000,Sometimes,Public_Transportation,Normal_Weight
4,Female,23,1.61,82.64,yes,yes,2.96,1.00,Sometimes,no,2.98,no,0.74,2.000,Sometimes,Public_Transportation,Obesity_Type_I
5,Female,26,1.61,104.85,yes,yes,3.00,3.00,Sometimes,no,2.61,no,0.07,0.779,Sometimes,Public_Transportation,Obesity_Type_III
6,Female,22,1.68,49.95,yes,yes,2.93,3.00,Frequently,no,2.79,no,0.63,1.366,no,Public_Transportation,Insufficient_Weight
7,Female,18,1.62,55.00,yes,yes,2.00,3.00,Frequently,no,1.00,no,1.00,1.000,no,Public_Transportation,Normal_Weight
8,Female,23,1.61,82.60,yes,yes,2.70,1.00,Sometimes,no,2.60,no,0.29,2.000,Sometimes,Public_Transportation,Obesity_Type_I
9,Female,18,1.74,50.00,no,yes,1.34,4.00,Frequently,no,1.00,no,2.00,1.000,Sometimes,Public_Transportation,Insufficient_Weight

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056 entries, 0 to 1055
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          1056 non-null   object
 1   Age                             1056 non-null   object
 2   Height                          1056 non-null   float64
 3   Weight                          1056 non-null   float64
 4   family_history_with_overweight  1056 non-null   object
 5   FAVC                            1056 non-null   object
 6   FCVC                            1019 non-null   float64
 7   NCP                             1056 non-null   float64
 8   CAEC                            1056 non-null   object
 9   SMOKE                           1056 non-null   object
 10  CH2O                            1056 non-null   float64
 11  SCC                             1056 non-null   object
 12  FAF                             1056 non-null   float64
 13  TUE                             1056 non-null   float64
 14  CALC                            1056 non-null   object
 15  MTRANS                          1030 non-null   object
 16  NObeyesdad                      1056 non-null   object
dtypes: float64(7), object(10)
memory usage: 140.4+ KB

In [148]:
df['Age'].unique()

array(['24', '23', '21', '22', '26', '18', '25', '20', '32', '20 years',
       '19', '38', '34', '44', '39', '22 years', '41', '31', '17 years',
       '17', '29', '42', '27', '16', '25 years', '40', '21 years', '33',
       '30', '37', '35', '36', '15', '19 years', '28', '55', '46',
       '36 years', '26 years', '45', '33 years', '43', '51', '48',
       '23 years', '14'], dtype=object)

In [149]:
df['Age'] = df['Age'].str.replace('years', '').str.strip()
df['Age'] = df['Age'].astype(int)

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056 entries, 0 to 1055
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          1056 non-null   object
 1   Age                             1056 non-null   int32
 2   Height                          1056 non-null   float64
 3   Weight                          1056 non-null   float64
 4   family_history_with_overweight  1056 non-null   object
 5   FAVC                            1056 non-null   object
 6   FCVC                            1019 non-null   float64
 7   NCP                             1056 non-null   float64
 8   CAEC                            1056 non-null   object
 9   SMOKE                           1056 non-null   object
 10  CH2O                            1056 non-null   float64
 11  SCC                             1056 non-null   object
 12  FAF                             1056 non-null   float64
 13  TUE                             1056 non-null   float64
 14  CALC                            1056 non-null   object
 15  MTRANS                          1030 non-null   object
 16  NObeyesdad                      1056 non-null   object
dtypes: float64(7), int32(1), object(9)
memory usage: 136.3+ KB

In [151]:
df.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,1056.000000,1056.000000,1056.000000,1019.000000,1056.000000,1056.000000,1056.000000,1056.000000
mean,24.235795,1.700066,86.497633,2.421374,2.651686,1.998002,0.987528,0.642227
std,6.321129,0.091560,26.181219,0.537591,0.804457,0.612930,0.850452,0.615533
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,20.000000,1.630000,66.000000,2.000000,2.525000,1.530000,0.110000,0.000000
50%,23.000000,1.700000,82.635000,2.390000,3.000000,2.000000,1.000000,0.583000
75%,26.000000,1.760000,107.965000,3.000000,3.000000,2.442500,1.602500,1.000000
max,55.000000,1.950000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [152]:
df.isna().sum()

Gender                             0
Age                                0
Height                             0
Weight                             0
family_history_with_overweight     0
FAVC                               0
FCVC                              37
NCP                                0
CAEC                               0
SMOKE                              0
CH2O                               0
SCC                                0
FAF                                0
TUE                                0
CALC                               0
MTRANS                            26
NObeyesdad                         0
dtype: int64

In [153]:
df = df.dropna()

In [154]:
df.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [155]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['NObeyesdad'])
y = df['NObeyesdad']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [156]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 795 entries, 968 to 116
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          795 non-null    object
 1   Age                             795 non-null    int32
 2   Height                          795 non-null    float64
 3   Weight                          795 non-null    float64
 4   family_history_with_overweight  795 non-null    object
 5   FAVC                            795 non-null    object
 6   FCVC                            795 non-null    float64
 7   NCP                             795 non-null    float64
 8   CAEC                            795 non-null    object
 9   SMOKE                           795 non-null    object
 10  CH2O                            795 non-null    float64
 11  SCC                             795 non-null    object
 12  FAF                             795 non-null    float64
 13  TUE                             795 non-null    float64
 14  CALC                            795 non-null    object
 15  MTRANS                          795 non-null    object
dtypes: float64(7), int32(1), object(8)
memory usage: 102.5+ KB

In [157]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 795 entries, 968 to 116
Series name: NObeyesdad
Non-Null Count  Dtype
--------------  -----
795 non-null    object
dtypes: object(1)
memory usage: 12.4+ KB

In [158]:
# Lakukan one-hot encoding untuk X (fitur kategorikal)
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# Pastikan kolom di X_train dan X_test sinkron
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [159]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [160]:
X_train

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,Gender_Male,...,SCC_yes,CALC_Always,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
968,33,1.59,60.00,3.00,1.00,2.00,0.00,0.000,True,False,...,False,False,False,False,True,False,False,False,True,False
984,30,1.70,102.59,2.65,1.08,1.35,0.33,0.387,False,True,...,False,False,False,False,True,False,False,False,True,False
709,23,1.73,82.48,2.71,2.85,1.53,1.00,0.174,False,True,...,False,False,False,True,False,False,False,False,True,False
820,23,1.74,105.00,3.00,3.00,2.00,1.00,0.000,False,True,...,False,False,False,True,False,False,False,False,True,False
970,28,1.80,119.05,2.74,3.00,2.48,0.68,0.678,False,True,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,26,1.62,102.23,3.00,3.00,1.07,0.03,1.000,True,False,...,False,False,False,True,False,False,False,False,True,False
295,31,1.58,68.00,2.00,1.00,1.00,1.00,0.000,True,False,...,False,False,False,True,False,False,False,False,True,False
920,33,1.72,72.75,2.00,3.00,1.00,0.00,1.339,True,False,...,False,False,False,True,False,True,False,False,False,False
472,23,1.75,55.97,2.48,3.37,2.00,2.00,0.327,True,False,...,False,False,False,False,True,False,False,False,True,False
116,26,1.64,111.60,3.00,3.00,2.65,0.00,0.251,True,False,...,False,False,False,True,False,False,False,False,True,False

In [161]:
y_train

array([1, 3, 6, 2, 3, 1, 0, 6, 5, 2, 4, 6, 0, 5, 1, 6, 4, 2, 2, 5, 2, 6,
       0, 1, 2, 2, 4, 6, 4, 2, 0, 6, 3, 6, 2, 3, 3, 5, 4, 3, 2, 0, 6, 0,
       2, 5, 1, 1, 1, 4, 4, 2, 1, 0, 2, 2, 0, 3, 5, 1, 6, 5, 2, 2, 4, 2,
       0, 5, 3, 4, 0, 4, 5, 1, 4, 4, 0, 2, 6, 0, 2, 4, 5, 6, 0, 3, 5, 2,
       1, 5, 2, 3, 4, 1, 5, 6, 4, 4, 2, 2, 2, 3, 4, 3, 3, 6, 0, 6, 5, 0,
       0, 2, 3, 2, 5, 6, 0, 6, 1, 1, 2, 5, 3, 2, 5, 4, 2, 5, 6, 2, 1, 5,
       1, 4, 4, 0, 1, 0, 1, 4, 6, 6, 5, 1, 4, 5, 3, 3, 5, 3, 1, 3, 6, 2,
       2, 0, 6, 2, 6, 3, 1, 3, 3, 4, 6, 4, 4, 0, 2, 0, 1, 0, 2, 6, 3, 2,
       3, 5, 0, 4, 6, 1, 0, 3, 1, 4, 2, 2, 3, 2, 5, 4, 1, 5, 4, 1, 3, 0,
       3, 1, 3, 0, 4, 5, 0, 5, 1, 6, 0, 0, 2, 4, 0, 5, 2, 0, 2, 1, 2, 3,
       4, 6, 0, 3, 3, 2, 6, 5, 3, 1, 1, 2, 4, 5, 6, 4, 4, 0, 6, 6, 1, 4,
       4, 6, 1, 3, 3, 6, 4, 1, 0, 1, 4, 1, 5, 1, 4, 3, 6, 0, 1, 0, 4, 0,
       0, 2, 6, 2, 6, 5, 0, 4, 1, 4, 5, 5, 5, 5, 6, 2, 0, 1, 2, 5, 6, 3,
       3, 3, 3, 5, 0, 4, 2, 2, 1, 2, 4, 6, 6, 5, 1, 2, 5, 0, 4, 2, 4, 1,
       3, 3, 1, 6, 2, 6, 0, 0, 5, 6, 0, 3, 5, 3, 0, 2, 1, 3, 0, 0, 2, 6,
       6, 4, 0, 3, 6, 3, 1, 0, 2, 3, 5, 3, 6, 3, 0, 2, 1, 6, 1, 3, 6, 4,
       6, 0, 5, 4, 5, 0, 3, 3, 2, 0, 1, 3, 4, 3, 5, 2, 3, 2, 3, 1, 0, 0,
       1, 3, 0, 5, 0, 5, 1, 4, 1, 1, 3, 2, 6, 2, 2, 1, 4, 6, 1, 1, 6, 4,
       2, 2, 1, 4, 5, 5, 1, 5, 6, 2, 1, 5, 0, 2, 6, 1, 1, 2, 1, 3, 2, 3,
       0, 1, 2, 4, 2, 4, 0, 6, 5, 0, 4, 0, 3, 2, 6, 2, 1, 1, 5, 5, 1, 6,
       4, 3, 3, 2, 2, 0, 1, 5, 2, 1, 1, 5, 6, 6, 1, 0, 4, 1, 6, 0, 5, 6,
       2, 0, 4, 2, 4, 2, 1, 3, 5, 3, 5, 5, 2, 4, 5, 2, 0, 2, 1, 1, 1, 3,
       6, 3, 6, 4, 2, 2, 6, 4, 1, 6, 0, 2, 1, 4, 6, 0, 2, 3, 6, 5, 2, 5,
       6, 1, 2, 4, 0, 1, 4, 6, 3, 1, 2, 3, 6, 4, 6, 4, 4, 5, 5, 0, 4, 1,
       2, 5, 1, 4, 6, 1, 2, 1, 6, 3, 5, 4, 4, 6, 0, 4, 5, 2, 3, 1, 4, 6,
       2, 1, 5, 4, 3, 6, 2, 1, 2, 4, 5, 1, 3, 2, 2, 4, 5, 0, 1, 2, 6, 2,
       6, 1, 0, 6, 3, 5, 1, 2, 0, 0, 2, 0, 2, 5, 4, 0, 3, 1, 2, 6, 4, 3,
       1, 3, 5, 0, 0, 5, 4, 2, 6, 0, 5, 0, 5, 4, 4, 3, 3, 4, 1, 0, 3, 2,
       6, 5, 0, 5, 2, 6, 5, 3, 3, 1, 5, 4, 4, 2, 2, 6, 3, 6, 3, 4, 6, 3,
       0, 2, 0, 1, 3, 1, 2, 4, 1, 4, 6, 4, 1, 3, 0, 2, 6, 1, 6, 3, 4, 3,
       4, 1, 4, 4, 6, 2, 3, 1, 3, 2, 4, 4, 2, 6, 2, 5, 3, 0, 3, 2, 4, 5,
       2, 2, 6, 6, 0, 4, 4, 3, 2, 0, 4, 2, 5, 6, 6, 2, 4, 3, 2, 1, 3, 2,
       3, 2, 2, 3, 4, 0, 1, 3, 1, 5, 1, 3, 4, 4, 1, 5, 3, 5, 5, 4, 6, 4,
       1, 5, 5, 1, 4, 6, 1, 4, 3, 6, 3, 6, 5, 3, 6, 4, 5, 5, 5, 2, 4, 6,
       6, 2, 3, 4, 4, 5, 4, 1, 1, 6, 4, 4, 4, 5, 4, 2, 5, 4, 5, 0, 5, 0,
       6, 3, 3, 0, 3, 4, 6, 4, 4, 2, 3, 1, 5, 3, 4, 2, 2, 4, 2, 6, 4, 6,
       5, 0, 4])

In [162]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [163]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [164]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [165]:
y_pred_lr = lr.predict(X_test)

In [166]:
y_pred_rf = rf.predict(X_test)

In [167]:
from sklearn.metrics import classification_report
print("Logistic Regression Classification Report:")
print(classification_report(y_test, y_pred_lr))

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        31
           1       0.74      0.77      0.76        22
           2       0.77      0.86      0.81        28
           3       0.97      0.97      0.97        33
           4       0.96      1.00      0.98        25
           5       0.83      0.78      0.81        32
           6       0.84      0.75      0.79        28

    accuracy                           0.86       199
   macro avg       0.86      0.86      0.86       199
weighted avg       0.87      0.86      0.86       199

In [168]:
print("Random Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        31
           1       0.79      1.00      0.88        22
           2       0.90      0.96      0.93        28
           3       1.00      1.00      1.00        33
           4       1.00      1.00      1.00        25
           5       1.00      0.84      0.92        32
           6       0.88      0.82      0.85        28

    accuracy                           0.94       199
   macro avg       0.94      0.94      0.94       199
weighted avg       0.95      0.94      0.94       199

In [169]:
from sklearn.metrics import accuracy_score
lr_acc = accuracy_score(y_test, y_pred_lr)
rf_acc = accuracy_score(y_test, y_pred_rf)


best_model = rf if rf_acc >= lr_acc else lr
best_model

RandomForestClassifier(random_state=42)

In [170]:
import pickle
with open("best_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

In [171]:
# Simpan label encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

# Simpan scaler
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# Simpan daftar kolom hasil one-hot encoding
# Harus dilakukan sebelum di-scale
X_columns = pd.get_dummies(X).columns.tolist()
with open("X_columns.pkl", "wb") as f:
    pickle.dump(X_columns, f)